---
HOSTS:
  el7server:
    roles:
    - server
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el6server:
    roles:
    - default
    - server
    platform: el-6-x86_64
    box: centos/6
    hypervisor: vagrant
  el7agent:
    roles:
    - agent
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el6agent:
    roles:
    - agent
    platform: el-6-x86_64
    box: centos/6
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  vagrant_memsize: 3072
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
